export {default as Weather } from './weather/Weather'
export {default as VideoUploadPage} from './VideoUploadPage'
export {default as Application} from './Application'
export {default as Calcula} from './Calcula'
export {default as Comments} from './comments'